
title: AskView
description: 여성패션, 뷰티, 홈인테리어, 가전디지털, 생활용품, 남성패션, 베이비패션, 여아패션, 남아패션, 스포츠패션, 신발, 패션잡화, 유아동, 식품, 주방용품, 레저, 자동차용품, 도서, 완구, 취미, 문구, 오피스, 식품, 반려동물
url: https://sangkuahn.github.io
img: https://i.ibb.co/10Rv9k8/ask-view-logo.jpg
img60: https://i.ibb.co/9vTZW6v/site-logo-60.png
img114: https://i.ibb.co/31J1vDF/site-logo-114.png
img144: https://i.ibb.co/8shnjtf/site-logo-144.png
img200: https://i.ibb.co/XjQKj9S/site-logo-200.png

permalink: ':title/'

markdown: kramdown
baseurl: "/"
baseWord: "제휴마케팅이 포함된 광고로 일정 커미션을 지급 받을 수 있습니다."
full-version: "https://sangkuahn.github.io"

sass:
    style: compressed



#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
analytics: 

# Comments
disqus-shortname: https-sangkuahn-github-io

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]
# exclude:
#   - _posts/
#   - _posts/1/
#   - _posts/2/
 

version: 0.8

paginate: 

plugins: 
    - jekyll-seo-tag    
